version: "3.6"
services:
  jenkins:
    build:
      context: jenkins
    ports:
      - 8081:8080
      - 50000:50000
    volumes: 
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - git-sever 
  git-server:
    build:
      dockerfile: ./gitserver/Dockerfile
      context: gitserver
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./gitserver/repos:/var/www/git
    links:
      - jenkins

volumes:
  jenkins-data:
    external: true